import type { Lang } from './ui';

export interface LegalParagraph {
  html: string;
  pending?: boolean;
}

export interface LegalSection {
  heading: string;
  paragraphs: LegalParagraph[];
}

export interface LegalDocument {
  title: string;
  description: string;
  notice: string;
  sections: LegalSection[];
}

interface LegalCopy {
  imprint: LegalDocument;
  privacy: LegalDocument;
}

const email = '<a href="mailto:info@onsano.com">info@onsano.com</a>';
const registrationNotice: Record<Lang, string> = {
  en: 'Onsano GmbH is in formation (i. Gr.). The company was founded by notarial deed on 2 September 2026; registration in the commercial register at the Local Court of Charlottenburg has been applied for.',
  de: 'Die Onsano GmbH befindet sich in Gründung (i. Gr.). Die Gesellschaft wurde am 2. September 2026 notariell gegründet; die Eintragung in das Handelsregister beim Amtsgericht Charlottenburg ist beantragt.',
  fr: 'Onsano GmbH est en cours de création (i. Gr.). La société a été constituée par acte notarié le 2 septembre 2026 ; son immatriculation au registre du commerce auprès du tribunal local de Charlottenburg a été demandée.',
  nl: 'Onsano GmbH is in oprichting (i. Gr.). De vennootschap is op 2 september 2026 bij notariële akte opgericht; de inschrijving in het handelsregister bij het Amtsgericht Charlottenburg is aangevraagd.',
  it: 'Onsano GmbH è in fase di costituzione (i. Gr.). La società è stata costituita con atto notarile il 2 settembre 2026; è stata richiesta l’iscrizione nel registro delle imprese presso l’Amtsgericht Charlottenburg.',
  es: 'Onsano GmbH está en proceso de constitución (i. Gr.). La sociedad se constituyó mediante escritura notarial el 2 de septiembre de 2026; se ha solicitado su inscripción en el registro mercantil del Amtsgericht Charlottenburg.',
};

export const legalCopy: Record<Lang, LegalCopy> = {
  en: {
    imprint: {
      title: 'Imprint',
      description: 'Imprint of Onsano.',
      notice: registrationNotice.en,
      sections: [
        { heading: 'Information pursuant to Section 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Germany' },
          { html: 'Registered office: Berlin' },
        ] },
        { heading: 'Represented by', paragraphs: [{ html: 'Managing directors: David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck. Each represents the company alone.' }] },
        { heading: 'Contact', paragraphs: [{ html: `Email: ${email}` }] },
        { heading: 'Commercial register', paragraphs: [
          { html: 'The company has been founded and registration has been applied for. The registration number will be added once the company is entered.', pending: true },
          { html: 'Register court: Local Court (Amtsgericht) Charlottenburg<br />Registration number: pending' },
        ] },
        { heading: 'Responsible for content pursuant to Section 18(2) of the German Interstate Media Treaty', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Liability for content', paragraphs: [{ html: 'As a service provider, we are responsible for our own content on these pages under the general laws pursuant to Section 7(1) DDG. Under Sections 8 to 10 DDG, however, we are not obliged to monitor transmitted or stored third-party information or investigate circumstances indicating unlawful activity. Obligations to remove or block the use of information under the general laws remain unaffected. Liability in this respect is only possible from the time we become aware of a specific legal infringement. If we become aware of such infringements, we will remove the content immediately.' }] },
        { heading: 'Liability for links', paragraphs: [{ html: 'Our website may contain links to external third-party websites over whose content we have no control. We therefore cannot accept liability for this external content. The respective provider or operator is always responsible for the content of linked pages. Linked pages were checked for possible legal violations when the links were created. Unlawful content was not apparent at that time. Continuous monitoring is not reasonable without specific indications of an infringement. If we become aware of legal violations, we will remove the relevant links immediately.' }] },
        { heading: 'Copyright', paragraphs: [{ html: 'Content and works created by the operators of these pages, including text, trademarks, logos and design, are subject to German copyright law. Reproduction, editing, distribution or any other use outside the limits of copyright law requires the written consent of the respective author or creator.' }] },
      ],
    },
    privacy: {
      title: 'Privacy policy',
      description: 'Privacy information for Onsano pursuant to Article 13 GDPR.',
      notice: registrationNotice.en,
      sections: [
        { heading: '1. Controller', paragraphs: [{ html: `The controller within the meaning of the General Data Protection Regulation (GDPR) is:<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Germany<br />Represented by the managing directors David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />Email: ${email}` }] },
        { heading: '2. Hosting and server log files', paragraphs: [{ html: 'This website is hosted on Cloudflare Pages (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare processes this data on our behalf (Article 28 GDPR) and is certified under the EU-U.S. Data Privacy Framework. When the website is accessed, the hosting provider automatically collects technically necessary information in server log files transmitted by your browser: IP address, date and time of the request, page accessed, amount of data transferred, referrer URL, browser type and version, and operating system. This processing ensures the reliable and secure operation of the website and is based on our legitimate interest under Article 6(1)(f) GDPR. Consent is not required. Log files are automatically deleted after a limited period and are not combined with other data sources.' }] },
        { heading: '3. Cookies and local storage', paragraphs: [{ html: 'The cookie banner itself does not set cookies. Your decision (accepted/declined) is stored as technically necessary information in your browser’s local storage. This is used only to avoid showing the banner again on your next visit and is permitted without separate consent under Section 25(2)(2) TTDSG and Article 6(1)(f) GDPR. Google Analytics cookies are set only after you expressly consent to the web analytics described in Section 4.' }] },
        { heading: '4. Web analytics (Google Analytics)', paragraphs: [{ html: 'We use Google Analytics, a web analytics service from Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland (or Google LLC, USA), only with your express consent under Article 6(1)(a) GDPR. Without consent, no analytics cookies are set and no data is transferred to Google. The script is loaded technically only after you click “Accept”. Google Analytics processes information including a shortened or anonymised IP address, device and browser information, pages visited, time spent and source of access to create pseudonymous usage statistics. Data may be transferred to the USA. Google participates in the EU-U.S. Data Privacy Framework or relies on standard contractual clauses [add details based on final configuration]. You may withdraw consent at any time for the future by selecting “Decline” in the banner or deleting this website’s local storage in your browser.' }] },
        { heading: '5. Appointment booking (Cal.com)', paragraphs: [{ html: 'We integrate the Cal.com booking service to arrange calls (Cal.com, Inc., USA [add exact provider information and data processing agreement]). When you book through the “Schedule a call” button, Cal.com processes the information you enter, generally your name, email address and chosen appointment, to complete the booking. The legal basis is Article 6(1)(b) GDPR for steps taken at your request before entering into a contract. Data may be transferred to the USA. Further information is available in Cal.com’s privacy policy. The booking module loads only when you actively click the relevant button.' }] },
        { heading: '6. Contact by email', paragraphs: [{ html: 'If you contact us by email, we process the data you provide, including your email address and the information in your message, solely to handle your enquiry. The legal basis is Article 6(1)(b) GDPR where the enquiry relates to entering into a contract; otherwise it is Article 6(1)(f) GDPR, based on our legitimate interest in responding to enquiries.' }] },
        { heading: '7. Fonts', paragraphs: [{ html: 'Fonts used on this website are self-hosted and delivered only from our own server or hosting provider. No connection is made to Google Fonts or other external font services, so no data, particularly your IP address, is transferred to third parties for this purpose when you visit the website.' }] },
        { heading: '8. Recipients and transfers to third countries', paragraphs: [{ html: 'Apart from the service providers named in Sections 2, 4 and 5, we do not disclose your data to third parties unless required by law. Where providers process data outside the EU/EEA, particularly in the USA, this is based on suitable safeguards such as the EU-U.S. Data Privacy Framework or standard contractual clauses under Article 46 GDPR.' }] },
        { heading: '9. Storage period', paragraphs: [{ html: 'We store personal data only for as long as required for the relevant processing purpose or by statutory retention obligations. Server log files are automatically deleted after a limited period. Analytics data is subject to the retention periods configured in Google Analytics [add final configuration].' }] },
        { heading: '10. Your rights', paragraphs: [{ html: `Subject to the statutory requirements, you have rights of access (Article 15 GDPR), rectification (Article 16), erasure (Article 17), restriction of processing (Article 18), data portability (Article 20), and objection to processing based on legitimate interests (Article 21). You may withdraw consent at any time for the future (Article 7(3)). Contact ${email}.` }] },
        { heading: '11. Right to complain to a supervisory authority', paragraphs: [{ html: 'You have the right to lodge a complaint with a data protection supervisory authority, in particular in the member state of your habitual residence, place of work or place of the alleged infringement (Article 77 GDPR). The authority responsible for us is the Bavarian State Office for Data Protection Supervision (BayLDA), Promenade 18, 91522 Ansbach, Germany.' }] },
        { heading: '12. Changes to this privacy policy', paragraphs: [{ html: 'We will update this privacy policy when changes in the law, the services used or the company structure, particularly following formation, make this necessary. The version published on this page at the time of your visit applies.' }] },
      ],
    },
  },
  de: {
    imprint: {
      title: 'Impressum',
      description: 'Impressum der Onsano.',
      notice: registrationNotice.de,
      sections: [
        { heading: 'Angaben gemäß § 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Deutschland' },
          { html: 'Sitz der Gesellschaft: Berlin' },
        ] },
        { heading: 'Vertreten durch', paragraphs: [{ html: 'Geschäftsführer: David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck, jeweils einzelvertretungsberechtigt.' }] },
        { heading: 'Kontakt', paragraphs: [{ html: `E-Mail: ${email}` }] },
        { heading: 'Registereintrag', paragraphs: [
          { html: 'Die Gesellschaft ist gegründet, die Eintragung ist beantragt. Die Registernummer wird nach der Eintragung ergänzt.', pending: true },
          { html: 'Registergericht: Amtsgericht Charlottenburg<br />Registernummer: Eintragung beantragt' },
        ] },
        { heading: 'Verantwortlich für den Inhalt nach § 18 Abs. 2 Medienstaatsvertrag', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Haftung für Inhalte', paragraphs: [{ html: 'Als Diensteanbieter sind wir gemäß § 7 Abs. 1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.' }] },
        { heading: 'Haftung für Links', paragraphs: [{ html: 'Unser Angebot enthält gegebenenfalls Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.' }] },
        { heading: 'Urheberrecht', paragraphs: [{ html: 'Die durch die Betreiber dieser Seiten erstellten Inhalte und Werke, darunter Texte, Marke, Bildmarke und Gestaltung, unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.' }] },
      ],
    },
    privacy: {
      title: 'Datenschutzerklärung',
      description: 'Datenschutzerklärung der Onsano gemäß Art. 13 DSGVO.',
      notice: registrationNotice.de,
      sections: [
        { heading: '1. Verantwortlicher', paragraphs: [{ html: `Verantwortlicher im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Deutschland<br />vertreten durch die Geschäftsführer David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />E-Mail: ${email}` }] },
        { heading: '2. Hosting und Server-Logfiles', paragraphs: [{ html: 'Diese Website wird bei Cloudflare Pages gehostet (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare verarbeitet die Daten in unserem Auftrag (Art. 28 DSGVO) und ist unter dem EU-U.S. Data Privacy Framework zertifiziert. Beim Aufruf der Website erhebt der Hosting-Anbieter automatisch technisch notwendige Informationen in sogenannten Server-Logfiles, die Ihr Browser übermittelt: IP-Adresse, Datum und Uhrzeit der Anfrage, aufgerufene Seite, übertragene Datenmenge, Referrer-URL, Browsertyp und -version sowie Betriebssystem. Diese Verarbeitung erfolgt zur Sicherstellung eines störungsfreien und sicheren Betriebs der Website und stützt sich auf unser berechtigtes Interesse gemäß Art. 6 Abs. 1 lit. f DSGVO. Eine Einwilligung ist hierfür nicht erforderlich. Die Logfiles werden automatisiert nach einer begrenzten Zeit gelöscht und nicht mit anderen Datenquellen zusammengeführt.' }] },
        { heading: '3. Cookies und lokale Speicherung', paragraphs: [{ html: 'Für den Cookie-Banner selbst setzen wir keine Cookies, sondern speichern Ihre Entscheidung (akzeptiert/abgelehnt) technisch notwendig im lokalen Speicher (Local Storage) Ihres Browsers. Diese Speicherung dient ausschließlich dazu, Ihnen den Banner bei erneutem Besuch nicht erneut anzuzeigen, und ist gemäß § 25 Abs. 2 Nr. 2 TTDSG bzw. Art. 6 Abs. 1 lit. f DSGVO ohne gesonderte Einwilligung zulässig. Erst wenn Sie der Webanalyse ausdrücklich zustimmen, werden die in Abschnitt 4 beschriebenen Cookies von Google Analytics gesetzt.' }] },
        { heading: '4. Webanalyse (Google Analytics)', paragraphs: [{ html: 'Wir setzen Google Analytics, einen Webanalysedienst der Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland (bzw. Google LLC, USA), ausschließlich nach Ihrer ausdrücklichen Einwilligung ein (Art. 6 Abs. 1 lit. a DSGVO). Ohne Einwilligung werden keine Analyse-Cookies gesetzt und keine Daten an Google übertragen; das entsprechende Skript wird technisch erst nach Klick auf „Accept“ nachgeladen. Google Analytics verarbeitet unter anderem IP-Adresse (gekürzt/anonymisiert), Geräte- und Browserinformationen, besuchte Seiten, Verweildauer und Herkunft des Zugriffs, um pseudonyme Nutzungsstatistiken zu erstellen. Dabei kann es zu einer Übermittlung von Daten in die USA kommen. Google hat sich hierfür dem EU-U.S. Data Privacy Framework unterworfen bzw. stützt die Übermittlung auf Standardvertragsklauseln [Details je nach finaler Konfiguration ergänzen]. Sie können Ihre Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen, indem Sie „Decline“ im Banner wählen oder die lokale Speicherung Ihres Browsers für diese Website löschen.' }] },
        { heading: '5. Terminbuchung (Cal.com)', paragraphs: [{ html: 'Für die Vereinbarung von Gesprächen binden wir den Buchungsdienst Cal.com ein (Cal.com, Inc., USA [genaue Anbieterangaben und AV-Vertrag ergänzen]). Wenn Sie über den Button „Gespräch vereinbaren“ einen Termin buchen, verarbeitet Cal.com die von Ihnen eingegebenen Daten, in der Regel Name, E-Mail-Adresse und der gewählte Termin, zur Durchführung der Terminbuchung. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Durchführung vorvertraglicher Maßnahmen auf Ihre Anfrage hin). Es kann hierbei zu einer Datenübermittlung in die USA kommen. Nähere Informationen entnehmen Sie der Datenschutzerklärung von Cal.com. Das Buchungsmodul wird erst geladen, wenn Sie den entsprechenden Button aktiv anklicken.' }] },
        { heading: '6. Kontaktaufnahme per E-Mail', paragraphs: [{ html: 'Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir die von Ihnen mitgeteilten Daten (u. a. Ihre E-Mail-Adresse und die Angaben in Ihrer Nachricht) ausschließlich zur Bearbeitung Ihrer Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage der Anbahnung eines Vertrags dient, andernfalls Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Beantwortung von Anfragen).' }] },
        { heading: '7. Schriftarten', paragraphs: [{ html: 'Die auf dieser Website verwendeten Schriftarten sind selbst gehostet und werden ausschließlich von unserem eigenen Server bzw. dem Hosting-Anbieter ausgeliefert. Es findet keine Verbindung zu Google Fonts oder anderen externen Schriftarten-Diensten statt. Bei Aufruf der Website werden also keine Daten (insbesondere Ihre IP-Adresse) zu diesem Zweck an Dritte übertragen.' }] },
        { heading: '8. Empfänger und Drittlandübermittlung', paragraphs: [{ html: 'Über die in den Abschnitten 2, 4 und 5 genannten Dienstleister hinaus geben wir Ihre Daten nicht an Dritte weiter, es sei denn, wir sind gesetzlich dazu verpflichtet. Soweit Dienstleister Daten außerhalb der EU/des EWR verarbeiten (insbesondere in den USA), erfolgt dies auf Grundlage geeigneter Garantien (z. B. EU-U.S. Data Privacy Framework, Standardvertragsklauseln gemäß Art. 46 DSGVO).' }] },
        { heading: '9. Speicherdauer', paragraphs: [{ html: 'Wir speichern personenbezogene Daten nur so lange, wie es für den jeweiligen Verarbeitungszweck erforderlich ist oder gesetzliche Aufbewahrungspflichten dies vorschreiben. Server-Logfiles werden nach einer begrenzten Zeit automatisiert gelöscht; Analyse-Daten unterliegen den bei Google Analytics konfigurierten Aufbewahrungsfristen [finale Konfiguration ergänzen].' }] },
        { heading: '10. Ihre Rechte', paragraphs: [{ html: `Ihnen stehen nach Maßgabe der gesetzlichen Bestimmungen folgende Rechte zu: Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16 DSGVO), Löschung (Art. 17 DSGVO), Einschränkung der Verarbeitung (Art. 18 DSGVO), Datenübertragbarkeit (Art. 20 DSGVO) sowie Widerspruch gegen die Verarbeitung aufgrund berechtigter Interessen (Art. 21 DSGVO). Erteilte Einwilligungen können Sie jederzeit mit Wirkung für die Zukunft widerrufen (Art. 7 Abs. 3 DSGVO). Wenden Sie sich hierzu an ${email}.` }] },
        { heading: '11. Beschwerderecht bei einer Aufsichtsbehörde', paragraphs: [{ html: 'Sie haben das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren, insbesondere in dem Mitgliedstaat Ihres gewöhnlichen Aufenthaltsorts, Ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes (Art. 77 DSGVO). Für uns zuständig ist das Bayerische Landesamt für Datenschutzaufsicht (BayLDA), Promenade 18, 91522 Ansbach.' }] },
        { heading: '12. Änderungen dieser Datenschutzerklärung', paragraphs: [{ html: 'Wir passen diese Datenschutzerklärung an, sobald Änderungen der Rechtslage, der eingesetzten Dienste oder der Unternehmensstruktur, insbesondere nach Abschluss der Gründung, dies erforderlich machen. Es gilt jeweils die zum Zeitpunkt Ihres Besuchs aktuelle, auf dieser Seite veröffentlichte Fassung.' }] },
      ],
    },
  },
  fr: {
    imprint: {
      title: 'Mentions légales',
      description: 'Mentions légales d’Onsano.',
      notice: registrationNotice.fr,
      sections: [
        { heading: 'Informations conformément à l’article 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Allemagne' },
          { html: 'Siège social : Berlin' },
        ] },
        { heading: 'Représentée par', paragraphs: [{ html: 'Gérants : David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck, chacun habilité à représenter seul la société.' }] },
        { heading: 'Contact', paragraphs: [{ html: `E-mail : ${email}` }] },
        { heading: 'Registre du commerce', paragraphs: [
          { html: 'La société est constituée et son immatriculation a été demandée. Le numéro d’immatriculation sera ajouté après l’inscription.', pending: true },
          { html: 'Tribunal d’enregistrement : Amtsgericht Charlottenburg<br />Numéro d’enregistrement : immatriculation en cours' },
        ] },
        { heading: 'Responsable du contenu conformément à l’article 18, paragraphe 2, du traité allemand sur les médias', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Responsabilité relative au contenu', paragraphs: [{ html: 'En tant que prestataire de services, nous sommes responsables de nos propres contenus sur ces pages conformément aux lois générales et à l’article 7, paragraphe 1, DDG. En vertu des articles 8 à 10 DDG, nous ne sommes toutefois pas tenus de surveiller les informations de tiers transmises ou stockées ni de rechercher des circonstances indiquant une activité illégale. Les obligations de suppression ou de blocage prévues par la législation générale restent inchangées. Une responsabilité ne peut naître qu’à partir du moment où nous avons connaissance d’une violation concrète. Dès qu’une telle violation est portée à notre connaissance, nous supprimons immédiatement le contenu concerné.' }] },
        { heading: 'Responsabilité relative aux liens', paragraphs: [{ html: 'Notre site peut contenir des liens vers des sites externes de tiers sur lesquels nous n’exerçons aucun contrôle. Nous ne pouvons donc assumer aucune responsabilité pour ces contenus. Le fournisseur ou l’exploitant des pages liées reste responsable de leur contenu. Les pages ont été vérifiées lors de la création des liens et aucun contenu illégal n’était alors identifiable. Un contrôle permanent n’est pas raisonnable sans indice concret de violation. Si une violation nous est signalée, nous supprimerons immédiatement les liens concernés.' }] },
        { heading: 'Droit d’auteur', paragraphs: [{ html: 'Les contenus et œuvres créés par les exploitants de ces pages, notamment les textes, marques, logos et éléments graphiques, sont soumis au droit d’auteur allemand. Toute reproduction, modification, diffusion ou utilisation au-delà des limites du droit d’auteur nécessite l’accord écrit de l’auteur ou du créateur concerné.' }] },
      ],
    },
    privacy: {
      title: 'Politique de confidentialité',
      description: 'Informations d’Onsano sur la protection des données conformément à l’article 13 du RGPD.',
      notice: registrationNotice.fr,
      sections: [
        { heading: '1. Responsable du traitement', paragraphs: [{ html: `Le responsable du traitement au sens du Règlement général sur la protection des données (RGPD) est :<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Allemagne<br />Représentée par ses gérants David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />E-mail : ${email}` }] },
        { heading: '2. Hébergement et journaux du serveur', paragraphs: [{ html: 'Ce site est hébergé sur Cloudflare Pages (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare traite ces données pour notre compte (article 28 du RGPD) et est certifiée dans le cadre du EU-U.S. Data Privacy Framework. Lors de l’accès au site, l’hébergeur collecte automatiquement les informations techniquement nécessaires transmises par votre navigateur dans des journaux serveur : adresse IP, date et heure de la requête, page consultée, volume de données transféré, URL de provenance, type et version du navigateur et système d’exploitation. Ce traitement garantit le fonctionnement fiable et sécurisé du site et repose sur notre intérêt légitime conformément à l’article 6, paragraphe 1, point f, du RGPD. Aucun consentement n’est requis. Les journaux sont automatiquement supprimés après une durée limitée et ne sont pas recoupés avec d’autres sources.' }] },
        { heading: '3. Cookies et stockage local', paragraphs: [{ html: 'La bannière de cookies elle-même ne dépose aucun cookie. Votre choix (accepté/refusé) est enregistré, lorsque cela est techniquement nécessaire, dans le stockage local de votre navigateur. Cet enregistrement sert uniquement à ne pas afficher de nouveau la bannière lors de votre prochaine visite et est autorisé sans consentement distinct conformément à l’article 25, paragraphe 2, point 2, TTDSG et à l’article 6, paragraphe 1, point f, du RGPD. Les cookies Google Analytics ne sont déposés qu’après votre consentement explicite à l’analyse décrite à la section 4.' }] },
        { heading: '4. Analyse d’audience (Google Analytics)', paragraphs: [{ html: 'Nous utilisons Google Analytics, un service de Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irlande (ou Google LLC, États-Unis), uniquement avec votre consentement explicite conformément à l’article 6, paragraphe 1, point a, du RGPD. Sans consentement, aucun cookie analytique n’est déposé et aucune donnée n’est transmise à Google. Le script n’est chargé qu’après un clic sur « Accepter ». Google Analytics traite notamment l’adresse IP raccourcie ou anonymisée, les informations sur l’appareil et le navigateur, les pages consultées, la durée de visite et l’origine de l’accès afin de créer des statistiques d’utilisation pseudonymisées. Des données peuvent être transférées aux États-Unis. Google participe au cadre UE-États-Unis de protection des données ou utilise des clauses contractuelles types [ajouter les détails selon la configuration finale]. Vous pouvez retirer votre consentement à tout moment pour l’avenir en choisissant « Refuser » dans la bannière ou en supprimant le stockage local de ce site dans votre navigateur.' }] },
        { heading: '5. Prise de rendez-vous (Cal.com)', paragraphs: [{ html: 'Nous intégrons le service Cal.com pour organiser des appels (Cal.com, Inc., États-Unis [ajouter les informations précises et l’accord de traitement]). Lorsque vous réservez via le bouton « Planifier un appel », Cal.com traite les données saisies, généralement votre nom, votre adresse e-mail et le rendez-vous choisi, afin d’effectuer la réservation. La base juridique est l’article 6, paragraphe 1, point b, du RGPD pour les mesures précontractuelles prises à votre demande. Des données peuvent être transférées aux États-Unis. Vous trouverez de plus amples informations dans la politique de confidentialité de Cal.com. Le module de réservation ne se charge qu’après un clic actif sur le bouton correspondant.' }] },
        { heading: '6. Contact par e-mail', paragraphs: [{ html: 'Si vous nous contactez par e-mail, nous traitons les données que vous fournissez, notamment votre adresse e-mail et le contenu de votre message, uniquement pour répondre à votre demande. La base juridique est l’article 6, paragraphe 1, point b, du RGPD lorsque la demande concerne la conclusion d’un contrat; dans les autres cas, il s’agit de l’article 6, paragraphe 1, point f, du RGPD, sur la base de notre intérêt légitime à répondre aux demandes.' }] },
        { heading: '7. Polices de caractères', paragraphs: [{ html: 'Les polices utilisées sur ce site sont auto-hébergées et fournies uniquement par notre serveur ou notre hébergeur. Aucune connexion n’est établie avec Google Fonts ou d’autres services externes de polices. Aucune donnée, notamment votre adresse IP, n’est donc transmise à des tiers à cette fin lors de votre visite.' }] },
        { heading: '8. Destinataires et transferts vers des pays tiers', paragraphs: [{ html: 'En dehors des prestataires mentionnés aux sections 2, 4 et 5, nous ne transmettons pas vos données à des tiers sauf obligation légale. Lorsque des prestataires traitent des données hors de l’UE/EEE, notamment aux États-Unis, le transfert repose sur des garanties appropriées, telles que le cadre UE-États-Unis de protection des données ou les clauses contractuelles types de l’article 46 du RGPD.' }] },
        { heading: '9. Durée de conservation', paragraphs: [{ html: 'Nous conservons les données personnelles uniquement pendant la durée nécessaire à la finalité concernée ou imposée par les obligations légales de conservation. Les journaux serveur sont automatiquement supprimés après une durée limitée. Les données analytiques sont soumises aux durées configurées dans Google Analytics [ajouter la configuration finale].' }] },
        { heading: '10. Vos droits', paragraphs: [{ html: `Sous réserve des conditions légales, vous disposez des droits d’accès (article 15 RGPD), de rectification (article 16), d’effacement (article 17), de limitation (article 18), de portabilité (article 20) et d’opposition aux traitements fondés sur l’intérêt légitime (article 21). Vous pouvez retirer votre consentement à tout moment pour l’avenir (article 7, paragraphe 3). Contactez ${email}.` }] },
        { heading: '11. Droit de réclamation', paragraphs: [{ html: 'Vous avez le droit d’introduire une réclamation auprès d’une autorité de contrôle de la protection des données, notamment dans l’État membre de votre résidence habituelle, de votre lieu de travail ou du lieu de la violation présumée (article 77 du RGPD). L’autorité compétente pour nous est l’Office bavarois de contrôle de la protection des données (BayLDA), Promenade 18, 91522 Ansbach, Allemagne.' }] },
        { heading: '12. Modifications de cette politique', paragraphs: [{ html: 'Nous mettrons cette politique à jour lorsque l’évolution du droit, des services utilisés ou de la structure de l’entreprise, notamment après sa création, l’exigera. La version publiée sur cette page au moment de votre visite s’applique.' }] },
      ],
    },
  },
  nl: {
    imprint: {
      title: 'Colofon',
      description: 'Colofon van Onsano.',
      notice: registrationNotice.nl,
      sections: [
        { heading: 'Informatie volgens § 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Duitsland' },
          { html: 'Statutaire zetel: Berlijn' },
        ] },
        { heading: 'Vertegenwoordigd door', paragraphs: [{ html: 'Bestuurders: David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck, elk zelfstandig vertegenwoordigingsbevoegd.' }] },
        { heading: 'Contact', paragraphs: [{ html: `E-mail: ${email}` }] },
        { heading: 'Handelsregister', paragraphs: [
          { html: 'De vennootschap is opgericht en de inschrijving is aangevraagd. Het registratienummer wordt na inschrijving toegevoegd.', pending: true },
          { html: 'Registerrechtbank: Amtsgericht Charlottenburg<br />Registratienummer: inschrijving aangevraagd' },
        ] },
        { heading: 'Verantwoordelijk voor de inhoud volgens § 18 lid 2 van het Duitse Medienstaatsvertrag', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Aansprakelijkheid voor inhoud', paragraphs: [{ html: 'Als dienstverlener zijn wij volgens § 7 lid 1 DDG en de algemene wetgeving verantwoordelijk voor onze eigen inhoud op deze pagina’s. Volgens §§ 8 tot en met 10 DDG zijn wij echter niet verplicht doorgegeven of opgeslagen informatie van derden te controleren of omstandigheden te onderzoeken die op onrechtmatige activiteiten wijzen. Verplichtingen om informatie op grond van de algemene wetgeving te verwijderen of te blokkeren blijven gelden. Aansprakelijkheid ontstaat pas vanaf het moment dat wij kennis hebben van een concrete overtreding. Zodra wij daarvan op de hoogte zijn, verwijderen wij de betreffende inhoud onmiddellijk.' }] },
        { heading: 'Aansprakelijkheid voor links', paragraphs: [{ html: 'Onze website kan links bevatten naar externe websites van derden waarop wij geen invloed hebben. Daarom kunnen wij voor die externe inhoud geen aansprakelijkheid aanvaarden. De betreffende aanbieder of beheerder blijft verantwoordelijk voor de inhoud van gekoppelde pagina’s. De pagina’s zijn bij het plaatsen van de link gecontroleerd op mogelijke overtredingen en er was toen geen onrechtmatige inhoud herkenbaar. Voortdurende controle is zonder concrete aanwijzingen niet redelijk. Zodra wij een overtreding vaststellen, verwijderen wij de betreffende links onmiddellijk.' }] },
        { heading: 'Auteursrecht', paragraphs: [{ html: 'De door de beheerders van deze pagina’s gemaakte inhoud en werken, waaronder teksten, merken, logo’s en vormgeving, vallen onder het Duitse auteursrecht. Reproductie, bewerking, verspreiding of ander gebruik buiten de grenzen van het auteursrecht vereist schriftelijke toestemming van de betreffende auteur of maker.' }] },
      ],
    },
    privacy: {
      title: 'Privacyverklaring',
      description: 'Privacy-informatie van Onsano volgens artikel 13 AVG.',
      notice: registrationNotice.nl,
      sections: [
        { heading: '1. Verwerkingsverantwoordelijke', paragraphs: [{ html: `Verwerkingsverantwoordelijke in de zin van de Algemene Verordening Gegevensbescherming (AVG) is:<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Duitsland<br />Vertegenwoordigd door de bestuurders David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />E-mail: ${email}` }] },
        { heading: '2. Hosting en serverlogbestanden', paragraphs: [{ html: 'Deze website wordt gehost op Cloudflare Pages (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare verwerkt deze gegevens in onze opdracht (artikel 28 AVG) en is gecertificeerd onder het EU-U.S. Data Privacy Framework. Bij het openen van de website verzamelt de hostingprovider automatisch technisch noodzakelijke informatie in serverlogbestanden die uw browser doorgeeft: IP-adres, datum en tijd van de aanvraag, opgevraagde pagina, hoeveelheid overgedragen gegevens, verwijzende URL, browsertype en -versie en besturingssysteem. Deze verwerking waarborgt een betrouwbare en veilige werking en is gebaseerd op ons gerechtvaardigd belang volgens artikel 6 lid 1 onder f AVG. Toestemming is niet vereist. Logbestanden worden na een beperkte periode automatisch verwijderd en niet met andere bronnen gecombineerd.' }] },
        { heading: '3. Cookies en lokale opslag', paragraphs: [{ html: 'De cookiebanner zelf plaatst geen cookies. Uw keuze (geaccepteerd/geweigerd) wordt, voor zover technisch noodzakelijk, opgeslagen in de lokale opslag van uw browser. Dit dient uitsluitend om de banner bij een volgend bezoek niet opnieuw te tonen en is zonder afzonderlijke toestemming toegestaan op grond van § 25 lid 2 nr. 2 TTDSG en artikel 6 lid 1 onder f AVG. Google Analytics-cookies worden pas geplaatst nadat u uitdrukkelijk instemt met de analyse in paragraaf 4.' }] },
        { heading: '4. Webanalyse (Google Analytics)', paragraphs: [{ html: 'Wij gebruiken Google Analytics, een dienst van Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ierland (of Google LLC, VS), uitsluitend met uw uitdrukkelijke toestemming volgens artikel 6 lid 1 onder a AVG. Zonder toestemming worden geen analysecookies geplaatst en geen gegevens aan Google overgedragen. Het script wordt pas geladen nadat u op “Accepteren” klikt. Google Analytics verwerkt onder meer een verkort of geanonimiseerd IP-adres, apparaat- en browsergegevens, bezochte pagina’s, verblijfsduur en herkomst om gepseudonimiseerde gebruiksstatistieken te maken. Gegevens kunnen naar de VS worden overgedragen. Google neemt deel aan het EU-VS Data Privacy Framework of gebruikt standaardcontractbepalingen [details toevoegen op basis van de definitieve configuratie]. U kunt uw toestemming voor de toekomst altijd intrekken door “Weigeren” te kiezen of de lokale opslag van deze website in uw browser te verwijderen.' }] },
        { heading: '5. Afspraken boeken (Cal.com)', paragraphs: [{ html: 'Wij integreren Cal.com om gesprekken te plannen (Cal.com, Inc., VS [precieze aanbiedergegevens en verwerkersovereenkomst toevoegen]). Wanneer u via “Gesprek inplannen” boekt, verwerkt Cal.com de door u ingevoerde gegevens, doorgaans naam, e-mailadres en gekozen afspraak, om de boeking uit te voeren. De rechtsgrond is artikel 6 lid 1 onder b AVG voor precontractuele maatregelen op uw verzoek. Gegevens kunnen naar de VS worden overgedragen. Meer informatie staat in de privacyverklaring van Cal.com. De boekingsmodule wordt pas geladen wanneer u actief op de betreffende knop klikt.' }] },
        { heading: '6. Contact per e-mail', paragraphs: [{ html: 'Wanneer u ons per e-mail benadert, verwerken wij de verstrekte gegevens, waaronder uw e-mailadres en de inhoud van uw bericht, uitsluitend om uw vraag te beantwoorden. De rechtsgrond is artikel 6 lid 1 onder b AVG wanneer de vraag betrekking heeft op het aangaan van een overeenkomst; anders artikel 6 lid 1 onder f AVG op basis van ons gerechtvaardigd belang om vragen te beantwoorden.' }] },
        { heading: '7. Lettertypen', paragraphs: [{ html: 'De lettertypen op deze website worden zelf gehost en uitsluitend geleverd door onze eigen server of hostingprovider. Er wordt geen verbinding gemaakt met Google Fonts of andere externe lettertypediensten. Bij een bezoek worden voor dit doel dus geen gegevens, in het bijzonder uw IP-adres, aan derden doorgegeven.' }] },
        { heading: '8. Ontvangers en doorgifte naar derde landen', paragraphs: [{ html: 'Afgezien van de dienstverleners in paragrafen 2, 4 en 5 geven wij uw gegevens niet aan derden door, tenzij de wet dit verplicht. Als dienstverleners gegevens buiten de EU/EER verwerken, met name in de VS, gebeurt dit op basis van passende waarborgen zoals het EU-VS Data Privacy Framework of standaardcontractbepalingen volgens artikel 46 AVG.' }] },
        { heading: '9. Bewaartermijn', paragraphs: [{ html: 'Wij bewaren persoonsgegevens alleen zolang dat voor het betreffende doel nodig is of wettelijke bewaarplichten dit vereisen. Serverlogbestanden worden na een beperkte periode automatisch verwijderd. Voor analysegegevens gelden de in Google Analytics ingestelde bewaartermijnen [definitieve configuratie toevoegen].' }] },
        { heading: '10. Uw rechten', paragraphs: [{ html: `Onder de wettelijke voorwaarden hebt u recht op inzage (artikel 15 AVG), rectificatie (artikel 16), wissing (artikel 17), beperking (artikel 18), overdraagbaarheid (artikel 20) en bezwaar tegen verwerking op basis van gerechtvaardigde belangen (artikel 21). U kunt toestemming altijd voor de toekomst intrekken (artikel 7 lid 3). Neem contact op via ${email}.` }] },
        { heading: '11. Recht om een klacht in te dienen', paragraphs: [{ html: 'U hebt het recht een klacht in te dienen bij een toezichthoudende autoriteit voor gegevensbescherming, met name in de lidstaat van uw gewone verblijfplaats, uw werkplek of de plaats van de vermeende inbreuk (artikel 77 AVG). De voor ons bevoegde autoriteit is het Beierse Staatsbureau voor toezicht op gegevensbescherming (BayLDA), Promenade 18, 91522 Ansbach, Duitsland.' }] },
        { heading: '12. Wijzigingen in deze privacyverklaring', paragraphs: [{ html: 'Wij passen deze privacyverklaring aan wanneer wijzigingen in de wet, de gebruikte diensten of de bedrijfsstructuur, met name na de oprichting, dit noodzakelijk maken. De versie die tijdens uw bezoek op deze pagina is gepubliceerd, is van toepassing.' }] },
      ],
    },
  },
  it: {
    imprint: {
      title: 'Note legali',
      description: 'Note legali di Onsano.',
      notice: registrationNotice.it,
      sections: [
        { heading: 'Informazioni ai sensi del § 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Germania' },
          { html: 'Sede legale: Berlino' },
        ] },
        { heading: 'Rappresentata da', paragraphs: [{ html: 'Amministratori: David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck, ciascuno con potere di rappresentanza disgiunta.' }] },
        { heading: 'Contatti', paragraphs: [{ html: `E-mail: ${email}` }] },
        { heading: 'Registro delle imprese', paragraphs: [
          { html: 'La società è costituita e l’iscrizione è stata richiesta. Il numero di registrazione sarà aggiunto dopo l’iscrizione.', pending: true },
          { html: 'Tribunale del registro: Amtsgericht Charlottenburg<br />Numero di registrazione: iscrizione richiesta' },
        ] },
        { heading: 'Responsabile dei contenuti ai sensi del § 18, comma 2, del trattato tedesco sui media', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Responsabilità per i contenuti', paragraphs: [{ html: 'In qualità di prestatore di servizi, siamo responsabili dei nostri contenuti su queste pagine ai sensi del § 7, comma 1, DDG e delle leggi generali. Ai sensi dei §§ 8-10 DDG non siamo tuttavia tenuti a monitorare informazioni di terzi trasmesse o memorizzate né a ricercare circostanze che indichino attività illecite. Restano invariati gli obblighi di rimozione o blocco previsti dalla legge. La responsabilità può sorgere solo dal momento in cui veniamo a conoscenza di una violazione concreta. In tal caso rimuoveremo immediatamente i contenuti interessati.' }] },
        { heading: 'Responsabilità per i link', paragraphs: [{ html: 'Il sito può contenere link a siti esterni di terzi sui cui contenuti non abbiamo alcun controllo. Non possiamo pertanto assumerci responsabilità per tali contenuti. Il rispettivo fornitore o gestore resta responsabile delle pagine collegate. Le pagine sono state controllate al momento della creazione del link e non risultavano contenuti illeciti. Un controllo continuo non è ragionevole senza indicazioni concrete di violazione. Qualora ne venissimo a conoscenza, rimuoveremo immediatamente i link interessati.' }] },
        { heading: 'Diritto d’autore', paragraphs: [{ html: 'I contenuti e le opere creati dai gestori di queste pagine, compresi testi, marchi, loghi e design, sono soggetti al diritto d’autore tedesco. La riproduzione, modifica, distribuzione o qualsiasi utilizzo oltre i limiti del diritto d’autore richiede il consenso scritto del rispettivo autore o creatore.' }] },
      ],
    },
    privacy: {
      title: 'Informativa sulla privacy',
      description: 'Informazioni sulla privacy di Onsano ai sensi dell’articolo 13 GDPR.',
      notice: registrationNotice.it,
      sections: [
        { heading: '1. Titolare del trattamento', paragraphs: [{ html: `Il titolare del trattamento ai sensi del Regolamento generale sulla protezione dei dati (GDPR) è:<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Germania<br />Rappresentata dagli amministratori David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />E-mail: ${email}` }] },
        { heading: '2. Hosting e file di log del server', paragraphs: [{ html: 'Questo sito è ospitato su Cloudflare Pages (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare tratta questi dati per nostro conto (articolo 28 GDPR) ed è certificata nell’ambito dell’EU-U.S. Data Privacy Framework. Quando si accede al sito, il provider raccoglie automaticamente nei log del server le informazioni tecnicamente necessarie trasmesse dal browser: indirizzo IP, data e ora della richiesta, pagina consultata, quantità di dati trasferiti, URL di provenienza, tipo e versione del browser e sistema operativo. Il trattamento garantisce il funzionamento affidabile e sicuro del sito e si basa sul nostro legittimo interesse ai sensi dell’articolo 6, paragrafo 1, lettera f, GDPR. Non è necessario il consenso. I log vengono cancellati automaticamente dopo un periodo limitato e non sono combinati con altre fonti.' }] },
        { heading: '3. Cookie e archiviazione locale', paragraphs: [{ html: 'Il banner dei cookie non imposta cookie. La scelta (accettata/rifiutata) viene memorizzata, ove tecnicamente necessario, nell’archiviazione locale del browser. Ciò serve esclusivamente a non mostrare nuovamente il banner alla visita successiva ed è consentito senza consenso separato ai sensi del § 25, comma 2, n. 2 TTDSG e dell’articolo 6, paragrafo 1, lettera f, GDPR. I cookie di Google Analytics vengono impostati solo dopo il consenso esplicito all’analisi descritta nella sezione 4.' }] },
        { heading: '4. Analisi web (Google Analytics)', paragraphs: [{ html: 'Utilizziamo Google Analytics, un servizio di Google Ireland Limited, Gordon House, Barrow Street, Dublino 4, Irlanda (o Google LLC, USA), esclusivamente con il consenso esplicito ai sensi dell’articolo 6, paragrafo 1, lettera a, GDPR. Senza consenso non vengono impostati cookie analitici né trasferiti dati a Google. Lo script viene caricato solo dopo aver fatto clic su “Accetta”. Google Analytics tratta, tra l’altro, un indirizzo IP abbreviato o anonimizzato, informazioni sul dispositivo e sul browser, pagine visitate, durata e provenienza dell’accesso per creare statistiche pseudonimizzate. I dati possono essere trasferiti negli USA. Google aderisce all’EU-U.S. Data Privacy Framework o utilizza clausole contrattuali standard [aggiungere dettagli in base alla configurazione finale]. Il consenso può essere revocato in qualsiasi momento per il futuro scegliendo “Rifiuta” nel banner o cancellando l’archiviazione locale del sito nel browser.' }] },
        { heading: '5. Prenotazione di appuntamenti (Cal.com)', paragraphs: [{ html: 'Integriamo Cal.com per organizzare chiamate (Cal.com, Inc., USA [aggiungere dati precisi del fornitore e accordo sul trattamento]). Quando prenoti tramite “Prenota una chiamata”, Cal.com tratta i dati inseriti, generalmente nome, indirizzo e-mail e appuntamento scelto, per eseguire la prenotazione. La base giuridica è l’articolo 6, paragrafo 1, lettera b, GDPR per misure precontrattuali adottate su richiesta. I dati possono essere trasferiti negli USA. Ulteriori informazioni sono disponibili nell’informativa sulla privacy di Cal.com. Il modulo viene caricato solo dopo un clic attivo sul pulsante.' }] },
        { heading: '6. Contatto via e-mail', paragraphs: [{ html: 'Se ci contatti via e-mail, trattiamo i dati forniti, compresi l’indirizzo e-mail e il contenuto del messaggio, esclusivamente per rispondere alla richiesta. La base giuridica è l’articolo 6, paragrafo 1, lettera b, GDPR se la richiesta riguarda la conclusione di un contratto; negli altri casi, l’articolo 6, paragrafo 1, lettera f, GDPR, sulla base del nostro legittimo interesse a rispondere.' }] },
        { heading: '7. Font', paragraphs: [{ html: 'I font utilizzati su questo sito sono ospitati localmente e forniti esclusivamente dal nostro server o dal provider di hosting. Non viene stabilita alcuna connessione con Google Fonts o altri servizi esterni. Durante la visita non vengono quindi trasferiti a terzi dati, in particolare l’indirizzo IP, per questo scopo.' }] },
        { heading: '8. Destinatari e trasferimenti verso paesi terzi', paragraphs: [{ html: 'Oltre ai fornitori indicati nelle sezioni 2, 4 e 5, non comunichiamo i dati a terzi salvo obbligo di legge. Se i fornitori trattano dati fuori dall’UE/SEE, in particolare negli USA, il trasferimento si basa su garanzie adeguate come l’EU-U.S. Data Privacy Framework o le clausole contrattuali standard ai sensi dell’articolo 46 GDPR.' }] },
        { heading: '9. Periodo di conservazione', paragraphs: [{ html: 'Conserviamo i dati personali solo per il tempo necessario alla relativa finalità o richiesto dagli obblighi legali. I log del server vengono eliminati automaticamente dopo un periodo limitato. Ai dati analitici si applicano i periodi configurati in Google Analytics [aggiungere configurazione finale].' }] },
        { heading: '10. I tuoi diritti', paragraphs: [{ html: `Alle condizioni di legge hai diritto di accesso (articolo 15 GDPR), rettifica (articolo 16), cancellazione (articolo 17), limitazione (articolo 18), portabilità (articolo 20) e opposizione ai trattamenti basati sul legittimo interesse (articolo 21). Puoi revocare il consenso in qualsiasi momento per il futuro (articolo 7, paragrafo 3). Contatta ${email}.` }] },
        { heading: '11. Diritto di reclamo', paragraphs: [{ html: 'Hai il diritto di presentare reclamo a un’autorità di controllo per la protezione dei dati, in particolare nello Stato membro in cui risiedi abitualmente, lavori o si è verificata la presunta violazione (articolo 77 GDPR). L’autorità competente per noi è l’Ufficio bavarese per la vigilanza sulla protezione dei dati (BayLDA), Promenade 18, 91522 Ansbach, Germania.' }] },
        { heading: '12. Modifiche all’informativa', paragraphs: [{ html: 'Aggiorneremo questa informativa quando cambiamenti della legge, dei servizi utilizzati o della struttura societaria, in particolare dopo la costituzione, lo renderanno necessario. Si applica la versione pubblicata su questa pagina al momento della visita.' }] },
      ],
    },
  },
  es: {
    imprint: {
      title: 'Aviso legal',
      description: 'Aviso legal de Onsano.',
      notice: registrationNotice.es,
      sections: [
        { heading: 'Información conforme al § 5 DDG', paragraphs: [
          { html: 'Onsano GmbH i. Gr.<br />Rüdesheimer Straße 11<br />80686 München<br />Alemania' },
          { html: 'Domicilio social: Berlín' },
        ] },
        { heading: 'Representada por', paragraphs: [{ html: 'Administradores: David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck, cada uno con facultad de representación individual.' }] },
        { heading: 'Contacto', paragraphs: [{ html: `Correo electrónico: ${email}` }] },
        { heading: 'Registro mercantil', paragraphs: [
          { html: 'La sociedad está constituida y se ha solicitado su inscripción. El número de registro se añadirá tras la inscripción.', pending: true },
          { html: 'Tribunal de registro: Amtsgericht Charlottenburg<br />Número de registro: inscripción solicitada' },
        ] },
        { heading: 'Responsable del contenido conforme al § 18, apartado 2, del tratado alemán de medios', paragraphs: [{ html: 'David Josef Alesch, Rüdesheimer Straße 11, 80686 München' }] },
        { heading: 'Responsabilidad por contenidos', paragraphs: [{ html: 'Como proveedor de servicios somos responsables de nuestros propios contenidos en estas páginas conforme al § 7, apartado 1, DDG y a las leyes generales. Sin embargo, conforme a los §§ 8 a 10 DDG no estamos obligados a supervisar información de terceros transmitida o almacenada ni a investigar circunstancias que indiquen una actividad ilícita. Las obligaciones legales de retirar o bloquear información no se ven afectadas. La responsabilidad solo puede surgir desde el momento en que tengamos conocimiento de una infracción concreta. Cuando tengamos conocimiento de ella, retiraremos inmediatamente el contenido correspondiente.' }] },
        { heading: 'Responsabilidad por enlaces', paragraphs: [{ html: 'Nuestro sitio puede contener enlaces a páginas externas de terceros sobre cuyo contenido no tenemos control. Por ello no podemos asumir responsabilidad por esos contenidos. El proveedor u operador correspondiente sigue siendo responsable de las páginas enlazadas. Las páginas fueron revisadas al crear los enlaces y no se detectó contenido ilícito. No resulta razonable una supervisión permanente sin indicios concretos de infracción. Si tenemos conocimiento de una infracción, retiraremos inmediatamente los enlaces correspondientes.' }] },
        { heading: 'Derechos de autor', paragraphs: [{ html: 'Los contenidos y obras creados por los operadores de estas páginas, incluidos textos, marcas, logotipos y diseño, están sujetos a la legislación alemana sobre derechos de autor. La reproducción, modificación, distribución o cualquier uso fuera de sus límites requiere el consentimiento escrito del autor o creador correspondiente.' }] },
      ],
    },
    privacy: {
      title: 'Política de privacidad',
      description: 'Información de privacidad de Onsano conforme al artículo 13 del RGPD.',
      notice: registrationNotice.es,
      sections: [
        { heading: '1. Responsable del tratamiento', paragraphs: [{ html: `El responsable del tratamiento en el sentido del Reglamento General de Protección de Datos (RGPD) es:<br />Onsano GmbH i. Gr., Rüdesheimer Straße 11, 80686 München, Alemania<br />Representada por los administradores David Josef Alesch, Sebastian Pietro Marie Graf von Kageneck<br />Correo electrónico: ${email}` }] },
        { heading: '2. Alojamiento y registros del servidor', paragraphs: [{ html: 'Este sitio se aloja en Cloudflare Pages (Cloudflare, Inc., 101 Townsend St, San Francisco, CA 94107, USA). Cloudflare trata estos datos por encargo nuestro (artículo 28 del RGPD) y está certificada en el marco del EU-U.S. Data Privacy Framework. Al acceder al sitio, el proveedor recopila automáticamente en registros del servidor la información técnicamente necesaria transmitida por el navegador: dirección IP, fecha y hora de la solicitud, página consultada, cantidad de datos transferidos, URL de referencia, tipo y versión del navegador y sistema operativo. El tratamiento garantiza un funcionamiento fiable y seguro y se basa en nuestro interés legítimo conforme al artículo 6.1.f del RGPD. No se requiere consentimiento. Los registros se eliminan automáticamente tras un periodo limitado y no se combinan con otras fuentes.' }] },
        { heading: '3. Cookies y almacenamiento local', paragraphs: [{ html: 'El banner de cookies no instala cookies. Su elección (aceptada/rechazada) se guarda, cuando es técnicamente necesario, en el almacenamiento local del navegador. Esto sirve únicamente para no volver a mostrar el banner en la siguiente visita y está permitido sin consentimiento separado conforme al § 25.2.2 TTDSG y al artículo 6.1.f del RGPD. Las cookies de Google Analytics solo se instalan después de que usted acepte expresamente el análisis descrito en la sección 4.' }] },
        { heading: '4. Analítica web (Google Analytics)', paragraphs: [{ html: 'Utilizamos Google Analytics, un servicio de Google Ireland Limited, Gordon House, Barrow Street, Dublín 4, Irlanda (o Google LLC, EE. UU.), únicamente con su consentimiento expreso conforme al artículo 6.1.a del RGPD. Sin consentimiento no se instalan cookies analíticas ni se transfieren datos a Google. El script solo se carga después de hacer clic en “Aceptar”. Google Analytics trata, entre otros datos, una dirección IP abreviada o anonimizada, información del dispositivo y navegador, páginas visitadas, duración y origen del acceso para crear estadísticas seudonimizadas. Los datos pueden transferirse a EE. UU. Google participa en el Marco de Privacidad de Datos UE-EE. UU. o utiliza cláusulas contractuales tipo [añadir detalles según la configuración final]. Puede retirar el consentimiento en cualquier momento para el futuro seleccionando “Rechazar” o borrando el almacenamiento local de este sitio en su navegador.' }] },
        { heading: '5. Reserva de citas (Cal.com)', paragraphs: [{ html: 'Integramos Cal.com para organizar llamadas (Cal.com, Inc., EE. UU. [añadir datos precisos y acuerdo de tratamiento]). Al reservar mediante “Agendar una llamada”, Cal.com trata los datos introducidos, generalmente nombre, correo electrónico y cita elegida, para completar la reserva. La base jurídica es el artículo 6.1.b del RGPD para medidas precontractuales solicitadas por usted. Los datos pueden transferirse a EE. UU. Encontrará más información en la política de privacidad de Cal.com. El módulo solo se carga cuando hace clic activamente en el botón correspondiente.' }] },
        { heading: '6. Contacto por correo electrónico', paragraphs: [{ html: 'Si nos contacta por correo electrónico, tratamos los datos facilitados, incluidos su dirección y el contenido del mensaje, únicamente para responder a su consulta. La base jurídica es el artículo 6.1.b del RGPD si la consulta se refiere a la celebración de un contrato; en los demás casos, el artículo 6.1.f del RGPD, basado en nuestro interés legítimo en responder.' }] },
        { heading: '7. Fuentes', paragraphs: [{ html: 'Las fuentes utilizadas en este sitio se alojan localmente y se suministran únicamente desde nuestro servidor o proveedor de alojamiento. No se establece conexión con Google Fonts ni con otros servicios externos. Por tanto, durante la visita no se transfieren a terceros datos, en particular su dirección IP, con este fin.' }] },
        { heading: '8. Destinatarios y transferencias a terceros países', paragraphs: [{ html: 'Salvo los proveedores indicados en las secciones 2, 4 y 5, no comunicamos sus datos a terceros a menos que la ley lo exija. Si los proveedores tratan datos fuera de la UE/EEE, especialmente en EE. UU., la transferencia se basa en garantías adecuadas, como el Marco de Privacidad de Datos UE-EE. UU. o las cláusulas contractuales tipo del artículo 46 del RGPD.' }] },
        { heading: '9. Plazo de conservación', paragraphs: [{ html: 'Conservamos los datos personales solo durante el tiempo necesario para la finalidad correspondiente o exigido por las obligaciones legales. Los registros del servidor se eliminan automáticamente tras un periodo limitado. Los datos analíticos están sujetos a los plazos configurados en Google Analytics [añadir configuración final].' }] },
        { heading: '10. Sus derechos', paragraphs: [{ html: `Con arreglo a la ley, tiene derecho de acceso (artículo 15 RGPD), rectificación (artículo 16), supresión (artículo 17), limitación (artículo 18), portabilidad (artículo 20) y oposición a tratamientos basados en intereses legítimos (artículo 21). Puede retirar el consentimiento en cualquier momento para el futuro (artículo 7.3). Contacte con ${email}.` }] },
        { heading: '11. Derecho a reclamar', paragraphs: [{ html: 'Tiene derecho a presentar una reclamación ante una autoridad de control de protección de datos, en particular en el Estado miembro de su residencia habitual, lugar de trabajo o lugar de la supuesta infracción (artículo 77 del RGPD). La autoridad competente para nosotros es la Oficina Estatal de Baviera para la Supervisión de la Protección de Datos (BayLDA), Promenade 18, 91522 Ansbach, Alemania.' }] },
        { heading: '12. Cambios en esta política', paragraphs: [{ html: 'Actualizaremos esta política cuando los cambios legales, de los servicios utilizados o de la estructura empresarial, especialmente tras la constitución, lo hagan necesario. Se aplica la versión publicada en esta página en el momento de su visita.' }] },
      ],
    },
  },
};
